job:
    path: /jobs
    defaults:
        _controller: App\Controller\JobController::jobList
ajax_route:
    path:     /showJob
    defaults:
        _controller: App\Controller\JobController::jobShow
    methods: [post]